name: Clinic WPF Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and UI Test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '9.0.x' 

    - name: Run NUKE
      run: ./build.ps1

    # 6. Upload Artifacts
    # Uses 'if: always()' so logs are uploaded even if the build/test fails
    - name: Upload Build and Test Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-and-test-logs
        path: |
          **/*.log
          **/*.e2e.tests/debug/*.png
          *.log
          TestResults/*.trx
        retention-days: 5
